-- generated by database functions generator automatically
-- for mysql 
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- Following lines remove old tables from database
DROP TABLE IF EXISTS`Parties`;
DROP TABLE IF EXISTS`Candidates`;
DROP TABLE IF EXISTS`Notifications`;

CREATE TABLE `Parties` (
`PartieId` INT  NOT NULL,
`Name` VARCHAR(20)  NOT NULL,
`Position` INT  NOT NULL,
`CreationTime` DATETIME  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `Parties` ADD PRIMARY KEY(`PartieId`); 
ALTER TABLE `Parties`  MODIFY `PartieId` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1; 

CREATE TABLE `Candidates` (
`CandidateId` INT  NOT NULL,
`Name` VARCHAR(20)  NOT NULL,
`Email` VARCHAR(20)  NOT NULL,
`Password` VARCHAR(20)  NOT NULL,
`Description` TEXT  NOT NULL,
`Role` VARCHAR(40)  NOT NULL,
`CreationTime` DATETIME  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `Candidates` ADD PRIMARY KEY(`CandidateId`); 
ALTER TABLE `Candidates`  MODIFY `CandidateId` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1; 

CREATE TABLE `Notifications` (
`NotificationId` INT  NOT NULL,
`Title` VARCHAR(15)  NOT NULL,
`CreationTime` DATETIME  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `Notifications` ADD PRIMARY KEY(`NotificationId`); 
ALTER TABLE `Notifications`  MODIFY `NotificationId` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1; 

